apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ammo-pvc
  namespace: tekst-stage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast
