on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    uses: NationalLibraryOfNorway/tekst-workflows/.github/workflows/node-build-and-deploy.yml@main
    with:
      ENVIRONMENT: "stage"
      NODE_VERSION: "20.17.0"
      BUILD_OUTPUT_PATH: ".next"
      SET_ENV: true
    secrets:
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}
      VAULT_SECRET_PATH: ${{ secrets.TEKST_VAULT_SECRET_PATH }}/data
      VAULT_ROLE_ID: ${{ secrets.TEKST_VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.TEKST_VAULT_SECRET_ID }}